# Generated by Django 3.1.6 on 2021-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBankApp', '0002_auto_20210209_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='situation',
            field=models.TextField(default='Please Be a helping hand!'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Positive', 'AB Positive'), ('AB Negative', 'AB Negative')], max_length=20, null=True),
        ),
    ]
